### PR TITLE
DBZ-1558

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://issues.redhat.com/browse/DBZ-1558

Supersedes #77

### CODE REVIEW

**Comment by lga-zurich** [comment]
@gunnarmorling regarding the lack of events: In the README.md the consumer is started on a topic for one table, but another table is modified. Easiest is to change line 331 from db2server.DB2INST1.CUSTOMERS to db2server.DB2INST1.PRODUCTS

Do you want a PR on gunnarmorling:DBZ-1558 for that ?

**Comment by gunnarmorling** [comment]
Hi, thanks, I tried an INSERT for customers as well as the original
statement for products, but I did only get the snapshot events in both
cases. That said, yes, the INSERT/UPDATE in the README should be for
customers, I'll change that.

>

**Comment by gunnarmorling** [comment]
Hey @lga-zurich, did you have a chance to look into this? Do you actually receive changes in the Kafka topic here?

**Comment by lga-zurich** [comment]
@gunnarmorling I do receive the changes, provided the topic in the REAME.md is changed as outlined above.

**Comment by gunnarmorling** [comment]
@lga-zurich still no luck :( I'm wondering -- how did you build your Kafka Connect image? Does this perhaps still contain the old binary you had built upfront?

@jpechane, @Naros, if you have a minute, could you give the tutorial instructions for DB2 a try? Note it requires to manually build the Connect image atm., as the 1.1 connector archive hasn't been deployed to Maven Central and thus the 1.1 container image doesn't contain it.

**Comment by Naros** [comment]
@gunnarmorling, I built the 1.1 image with the DB2 connector and I too did not see any messages arrive in the topic after I issued the `INSERT` statement.

**Comment by gunnarmorling** [comment]
Thanks for checking, @Naros. @lga-zurich, could you perhaps remove all related container images and start with a clean build, so to make sure we're all looking at the same thing?

**Comment by jpechane** [comment]
Tested from scratch and works for me, applying.

**Comment by lga-zurich** [comment]
Thanks for checking @jpechane 

@gunnarmorling it just works for me. Just in case:
> $ docker --version
> Docker version 19.03.6, build 369ce74a3c
> $ docker-compose --version
> docker-compose version 1.25.3, build d4d1b42b
> $ uname -a
> Linux localhost.localdomain 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> $ cat /etc/redhat-release
> CentOS Linux release 7.7.1908 (Core)

One has to be careful that the DB is up and running and the CDC active. Maybe we can provide a hint as to when that's actually the case.

**Pull request merged**
