### PR TITLE
[Draft] DBZ-4302 Added an example for MongoDB Outbox Event Router

### PR DESCRIPTION
**Pull request by sgc109**
https://issues.redhat.com/browse/DBZ-4302

---

follow-up for debezium/debezium#2877

### CODE REVIEW

**Review by gunnarmorling — COMMENTED** [review]
Very nice, this looks great. We only should update to the tagged version once 1.8.0.Beta1 is out (planned for Thursday this week). And did you actually test the tracing integration? As we don't start a span in the source application, the tracing span should start at the point when the transaction got committed.

**Comment by gunnarmorling** [comment]
@sgc109, which MongoDB version are you using? I'm getting this error in the mongo logs:

```
mongodb_1    | {"t":{"$date":"2021-11-22T09:26:00.906+00:00"},"s":"I",  "c":"-",        "id":4939300, "ctx":"monitoring-keys-for-HMAC","msg":"Failed to refresh key cache","attr":{"error":"NotYetInitialized: Cannot use non-local read concern until replica set is finished initializing.","nextWakeupMillis":6800}}
```

Did you encounter that too?

**Comment by sgc109** [comment]
@gunnarmorling, Yes, I encounter that too, it seems to occur literally because replica set is not initialized as it says, so it would have to stop to occur right after you run the next command in README, which executes shell script including replica set initialization process in docker container.

**Comment by gunnarmorling** [comment]
Thanks a lot, @sgc109. Rebased and applied. Pushed one more commit with a few minor adjustments. That issue above was a stupid user mistake on my end; all looking good now. Thanks again for this great contribution!

**Pull request closed without merging**
