### PR TITLE
DBZ-1994 Update OpenShift example to OpenShift 4

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.redhat.com/browse/DBZ-1994

### CODE REVIEW

**Comment by vjuranek** [comment]
@gunnarmorling do you want me to add k8s secret into this example as well or keep it as simple as possible (and eventually link the documentation how to do that)? Personally I would keep it simple, as adding secret is possible source of issues when user start playing with it (it took me quite some time to figure out that encoding login and password with `echo 'passoword'|base64` returns wrong encoded value because `echo` adds new line to the string, and there are probably more possible pitfalls like this).

**Comment by vjuranek** [comment]
Updated example also with secret configuration.

**Comment by vjuranek** [comment]
Updated example also with secret configuration.

**Comment by gunnarmorling** [comment]
Excellent, thanks a lot!

**Pull request merged**
