### PR TITLE
Debezium Engine with WebAssembly client

### PR DESCRIPTION
**Pull request by jpechane**

### CODE REVIEW

**Comment by rk3rn3r** [comment]
Wow!

**Review by vjuranek — APPROVED** [review]
Very nice!

**Comment by mfvitale** [comment]
Interesting!

**Comment by bhelx** [comment]
Would be great to see this land :)

**Review by Naros — APPROVED** [review]
This is super neat, and I concur with @mfvitale, and can't wait for a blog post about this gem! :tada:

**Comment by jpechane** [comment]
Added improvements by @andreaTP - removal of WASI dependency via https://github.com/jpechane/debezium-examples/pull/1

**Comment by jpechane** [comment]
@bhelx No worries, it will come :-)

**Pull request merged**
