### PR TITLE
[Distributed Caching] Version update

### PR DESCRIPTION
**Pull request by gunnarmorling**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @karesti, so this does the version update to the current Quarkus and Infinispan for our caching demo. It mostly works as it should, only querying in the ISPN console is broken. I'm getting the following error:

```
Query error
Error executing search java.lang.RuntimeException: protostream.com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
```

Any idea what could be wrong?

**Comment by gunnarmorling** [comment]
@karesti, in the commit before that (https://github.com/debezium/debezium-examples/commit/51ee3cceb2ccb2e2e03ef0143a40931ee6146902, already merged to _main_), I added a new field `version` to the `PurchaseOrder` entity. I'm wondering whether that could be related, perhaps I did something wrong in terms of the cache/ProtoBuf configuration there?

**Comment by gunnarmorling** [comment]
Rebased an applied. Thanks a lot @karesti for all your help with the updates, everything works like a charm now. This will come in very handy when doing the DBZ + ISPN talk next time 🙏.

**Comment by karesti** [comment]
@gunnarmorling perfect!!!!

**Pull request closed without merging**
