### PR TITLE
Debezium Embedded with NATS Example

### PR DESCRIPTION
**Pull request by Wang-Yu-Chao**
a example using Debezium Embedded to capture change data events from
databases to NATS stream.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @Wang-Yu-Chao, thanks a lot! I had been planning to look up on NATS for quite some time, so it's super-cool to see this example here. Would you perhaps be interested in writing a small blog post about this on debezium.io, too?

**Comment by Wang-Yu-Chao** [comment]
@gunnarmorling Very glad to do that! I've looked through your blog about Debezium with Amazon Kinesis. Could I write a similar one? Hope you don't mind my imitation.

**Comment by Wang-Yu-Chao** [comment]
Hi @gunnarmorling. I just finished my blog about this PR. May I ask how to post it on debezium.io?

**Comment by gunnarmorling** [comment]
Rebased and applied; thanks a lot, @Wang-Yu-Chao (and sorry for the delay of processing this).

**Comment by gunnarmorling** [comment]
Regarding the blog post, we have discussed the matter again internally and decided against a blog post on this. I'm really sorry for the effort on your side :( I can tell you in our call later this week about the reasons.

**Comment by gedw99** [comment]
@Wang-Yu-Chao 
Wow great timing. I am also looking to do CDC with NATS.
Can you also let me know where you publish the article.

**Comment by gedw99** [comment]
@gunnarmorling There is an example doing it with PostreSQL ad NATS also here:
https://github.com/jensneuse/PostgresLogicalReplicationExample

**Pull request closed without merging**
