### PR TITLE
Update Prometheus JMX Exporter config rules for mult-partition connector mode

### PR DESCRIPTION
**Pull request by dude0001**

### CODE REVIEW

**Comment by dude0001** [comment]
Should I target 2.x branch instead of main?

**Comment by jpechane** [comment]
@dude0001 No, the `main` is correct. The `2.x` branch was used for 1.x -> 2.x migration.

**Comment by jpechane** [comment]
@dude0001 Thanks for the PR. I did a force push to update commit message.
Will this update work for non-partitioned connectors - like MySQL too? If not could you please modify it so it works for both types?

**Comment by Naros** [comment]
I recently updated the monitoring example to support multi-partition and non-partitioned connectors, so I believe this PR is not obsolete.  @dude0001 could you check and verify if that's accurate and close if so?

**Comment by dude0001** [comment]
Your change looks good to me @Naros, thank you for updating it.

**Pull request closed without merging**
