### PR TITLE
DBZ-1709 [outbox] Upgrade to Debezium 1.6 and Quarkus 2.0

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-1709

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@Naros, what's missing to un-draft this one? Btw. related to outbox, the same set of changes could be done to the the Saga example, which uses the outbox extension in all of its three services.

**Comment by Naros** [comment]
I'll take a look at the Saga example and add those to this PR since they're somewhat related in that regard.

**Comment by gunnarmorling** [comment]
Gotcha, makes sense.

Another thing (and feel free to reject it due to scope creep): how about adding a basic GitHub Actions workflow for compiling asorted examples upon PRs and pushes to master? Could even be just the outbox and saga ones to begin with, as you see fit. Compilation itself isn't a great assurance for these examples to work, but it's a first step and we can expand over time. WDYT?

**Comment by Naros** [comment]
You actually read my mind as I had just looked at that Jira on that very topic :P

**Comment by gunnarmorling** [comment]
Hehe, cool. Great minds think alike :)

**Comment by Naros** [comment]
@gunnarmorling I would have expected the workflows to have triggered on this PR since they're included but they were not.  AFAICT I don't think I've missed anything for them, do you see anything I could have missed?

**Comment by gunnarmorling** [comment]
> this will take effect in this repository only once they're merged

Yes, I think that's the case.

**Review by gunnarmorling — APPROVED** [review]
LGTM; just merge yourself once you feel it's ready. Thx!

**Pull request merged**
