### PR TITLE
[monitoring] Show all connectors in dashboard

### PR DESCRIPTION
**Pull request by jpechane**

### CODE REVIEW

**Comment by jpechane** [comment]
@gunnarmorling Just a small improvement

**Comment by gunnarmorling** [comment]
Cool; btw. do we have a blog post on this one yet?

**Comment by jpechane** [comment]
@gunnarmorling I must admit that I don't remeber it but I think we don't

**Comment by gunnarmorling** [comment]
Could be a nice topic then :) But lesser in terms of prio than some others
we've already planned and discussed.

>

**Pull request merged**
