### PR TITLE
[fk-joins] Version updates

### PR DESCRIPTION
**Pull request by gunnarmorling**
@ani-sha, this does a version update for the FK join example; also the host name variable isn't needed any longer with this. Could you give this one a try? Thanks!

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@ani-sha, can this one be merged?

**Comment by ani-sha** [comment]
@gunnarmorling It works with `1.11.2.Final` for me.

**Comment by gunnarmorling** [comment]
Ah, 1.12.0.Final is out by now. Could you verify with that one too and push
a commit for this if it also works (it really should)?

>

**Comment by ani-sha** [comment]
```
! [remote rejected] gunnarmorling/fk-join-update -> gunnarmorling/fk-join-update (permission denied)
error: failed to push some refs to 'https://github.com/gunnarmorling/debezium-examples.git'
```
@gunnarmorling I don't have permission.

**Comment by ani-sha** [comment]
Oops! Done! :sweat_smile: 
@gunnarmorling  This works.

**Pull request merged**
